### ISSUE TITLE
0.8.7 missing importlib-metadata

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/filesystem-spec-feedstock#42]
Hey folks, thanks for maintaining this!

[Downstream](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=283441&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=3054), I'm trying to keep some nasty envs in `pip check`, and (I presume) most recent `fsspec` is complaining at me:

```
python -m pip check
fsspec 0.8.7 requires importlib-metadata, which is not installed.
```

I'll hack up a PR presently...

**Comment by martindurant** [comment]
This is an optional requirement and python-version dependant.

On February 27, 2021 12:23:59 PM EST, Nicholas Bollweg <notifications@github.com> wrote:
>Hey folks, thanks for maintaining this!
>
>[Downstream](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=283441&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=3054),
>I'm trying to keep some nasty envs in `pip check`, and (I presume) most
>recent `fsspec` is complaining at me:
>
>```
>python -m pip check
>fsspec 0.8.7 requires importlib-metadata, which is not installed.
>```
>
>I'll hack up a PR presently...
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/conda-forge/filesystem-spec-feedstock/issues/42

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bollwyvl** [comment]
I guess the extra needs a name before the : to be optional? I'm not super
familiar with the extras mini language...

**Comment by bollwyvl** [comment]
Anyhow, we have that noop/noarch importlib_metadata so it doesn't break
things in the field.

**Comment by zklaus** [comment]
While this does appear in `extra_requires`, it seems to be a general requirement for Python <3.8. Indeed, perhaps this requirement should be changed upstream, but for now I suggest to address this in this conda-forge package. Will make a PR suggestion.

**Comment by martindurant** [comment]
> it seems to be a general requirement for Python <3.8.

It is not! fsspec works just fine without it.

**Comment by zklaus** [comment]
Seems this is resolved now. But the way it is written up to and including the 0.9.0 release, as far as setuptools is concerned, it is a general dependency, i.e. this is how `extras_require = {":python_version < '3.8'": ["importlib_metadata"],}` is interpreted due to the empty string before the first `:`.

**Comment by maresb** [comment]
Thanks so much @zklaus for your work on this!!!

Would it be possible to add the `pip check` test like shown [here](https://github.com/bollwyvl/filesystem-spec-feedstock/blob/85b40a6fc170a503def7594e348ddc1681e3adbc/recipe/meta.yaml#L25-L31)?

**Comment by martindurant** [comment]
OK, I see. That line was included when I specifically objected to inclusion in requirements.txt, but apparently it does the same thing.

**Comment by zklaus** [comment]
> Thanks so much @zklaus for your work on this!!!
> 
> Would it be possible to add the `pip check` test like shown [here](https://github.com/bollwyvl/filesystem-spec-feedstock/blob/85b40a6fc170a503def7594e348ddc1681e3adbc/recipe/meta.yaml#L25-L31)?

Good idea! I added the commits from that branch best I could. Let's see if it works.

**Comment by maresb** [comment]
Could we please reopen this? Unfortunately this problem persists.

The automated tests for this feedstock are only running on Python 3.9. Unfortunately I see that [here](https://github.com/conda-forge/dvc-feedstock/pull/211) that it is still failing on Python 3.6 and 3.7.

(I did indeed check that these failed tests downloaded the current 2-hour old build `fsspec-0.9.0-pyhd8ed1ab_1`.)

**Comment by martindurant** [comment]
So what needs to happen? If I just rerelease the three packages, will this go away?

**Comment by maresb** [comment]
Adding `importlib-metadata` as a dependency will make it go away.

The fancy tricks with setuptools I am unfortunately not understanding. I was hoping that someone would come up with a slick solution here. But given [this patch](https://github.com/conda-forge/filesystem-spec-feedstock/blob/master/recipe/patches/0001-Make-metadata-dep-an-exrta.patch), the `setuptools.setup` command seems to be equivalent to what you have in master. Thus I don't believe a rerelease will fix things.

**Comment by martindurant** [comment]
importlib-metadata is not a dependency. That patch makes it clear.

**Comment by maresb** [comment]
I just cloned your repo with a fresh Python 3.7 install. Pip check passes, so I agree with you. I don't know why it's failing in this build.

**Comment by maresb** [comment]
I noticed that in the source distribution on PyPI (which this feedstock uses), the file `/fsspec-0.9.0/fsspec.egg-info/requires.txt` contains:
```ini
[:python_version < '3.8']
importlib_metadata
```
It seems plausible to me that `setup.py` isn't running, but instead it's using this `requires.txt` which is causing the dependency.

If my current hypothesis is correct, then I was wrong before, and probably a new release would fix things.

**Comment by zklaus** [comment]
Good points. I tried to create a better patch by going through the motions of doing a `python setup.py sdist`. Let's see what comes of it.
